Roy/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chekigari.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chekigari/urls.py
from django.urls import path
from . import views

app_name = "chekigari"  # prevents namespace conflict. always include it
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginform, name='login'),
    path('register/', views.register, name='register'),
    path('viewdata/', views.viewdata, name='viewdata'),
    path('insert', views.insert, name="insert"),  # Performs the registration of new users
    path('contact/', views.contact, name='contact'),
    path('sendMessage', views.sendMessage, name='sendMessage'),
    path('delete/<id>', views.delete, name='delete'),
    path('viewmessages/', views.viewMessages, name='viewMessages'),
    path('deleteMessage/<id>', views.deleteMessage, name='deleteMessage'),
    path('edituser/<id>', views.edituser, name="edituser"),
    path('shopcars/', views.shop, name='shop'),
    path('signup/', views.signup, name='signup'),  # Renders the signup form
    path('signupdata', views.signupdata, name='signupdata'),  # performs the signup action
    path('userlogin', views.userlogin, name='userlogin'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('viewvehicle/', views.viewvehicle, name='viewvehicle'),
    path('cart/', views.cart, name='cart'),  # Renders the cart file
    path('uploads/', views.uploads, name='uploads'),
    path('addvehicle/', views.addvehicle, name='addvehicle'),
    path('addvehicletodb', views.addvehicletodb,  name='addvehicletodb'),
    path('uploadfiles', views.uploadfiles, name='uploadfiles')

]

chekigari/models.py
from django.db import models


# Create your models here.
# SQl database are divided into different categories: MySQl, SQlite


class Users(models.Model):
    fname = models.CharField(max_length=25, blank=False, null=False)
    onames = models.CharField(max_length=25, blank=False, null=False)
    phone = models.IntegerField()
    dob = models.CharField(max_length=25, blank=False, null=False)
    email = models.EmailField()
    country = models.CharField(max_length=25, blank=False, null=False)
    gender = models.CharField(max_length=6, blank=False, null=False)

    def __str__(self):
        return self.fname


class Messages(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    phone = models.IntegerField()
    subject = models.CharField(max_length=50, blank=False, null=False)
    message = models.CharField(max_length=250, blank=False, null=False)

    def __str__(self):
        return self.name


class Uploadfiles(models.Model):
    image = models.ImageField(upload_to="images/", blank=True, null=True)
    file = models.FileField(upload_to="uploaded_files/", blank=True, null=True)

    def __str__(self):
        return self.image


class Shop(models.Model):
    make = models.CharField(max_length=20, null=False, blank=False)
    model = models.CharField(max_length=20, null=False, blank=False)
    cc = models.IntegerField()
    mileage = models.IntegerField()
    fuel_type = models.CharField(max_length=10, null=False, blank=False)
    transmission = models.CharField(max_length=20, null=False, blank=False)
    year = models.IntegerField()
    color = models.CharField(max_length=20, null=False, blank=False)
    available_units = models.IntegerField()
    photo = models.ImageField(upload_to="shopvehicles/", blank=True, null=True)
    # price = models.IntegerField()

    # other_photos = models.ImageField(upload_to='shopvehicles/', blank=True, null=True)


    def __str__(self):
        return self.make

chekigari/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Users, Messages, Uploadfiles, Shop
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login


# from static.images import views


# Create your views here.


def loginform(request):
    return render(request, 'login.html')


def index(request):
    vehicles = Shop.objects.all()
    context = {"vehicles":vehicles, 'nav': 'home'}
    return render(request, 'index.html', context)


def register(request):
    return render(request, 'register.html')


def viewdata(request):
    data = Users.objects.all()
    intersex = Users.objects.filter(gender="Intersex").count()
    male = Users.objects.all().count()

    context = {"data": data, "intersex": intersex, "male": male}

    return render(request, 'view.html', context)


def contact(request):
    return render(request, 'contact.html')


def insert(request):
    if request.method == 'POST':
        fname = request.POST.get('first-name').title()
        onames = request.POST.get('other-names').title()
        phone = request.POST.get('tel-no')
        dob = request.POST.get('dob')
        email = request.POST.get('email').lower()
        country = request.POST.get('country')
        gender = request.POST.get('gender')
        reg = Users(fname=fname, onames=onames, phone=phone, dob=dob, email=email, country=country, gender=gender)
        reg.save()

        messages.success(request, 'Registration successful')

    return redirect('/register')


def sendMessage(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone_no')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        query = Messages(name=name, phone=phone, subject=subject, message=message)
        query.save()
        messages.success(request, 'Message sent successfully')

    return render(request, 'contact.html')


def delete(request, id):
    d = Users.objects.get(id=id)
    d.delete()

    messages.success(request, 'User deleted successfully')

    return redirect("/viewdata")


def viewMessages(request):
    viewmessages = Messages.objects.all()
    context = {"viewmessages": viewmessages}

    return render(request, 'viewmessages.html', context)


def deleteMessage(request, id):
    deleteMessage = Messages.objects.get(id=id)
    deleteMessage.delete()

    messages.success(request, 'Message deleted successfully')

    return redirect("/viewmessages")


def edituser(request, id):
    if request.method == "POST":
        fname = request.POST['first-name']
        onames = request.POST['other-names']
        phone = request.POST['tel-no']
        dob = request.POST['dob']
        email = request.POST['email']
        country = request.POST['country']
        gender = request.POST['gender']

        update = Users.objects.get(id=id)
        update.fname = fname
        update.onames = onames
        update.phone = phone
        update.dob = dob
        update.email = email
        update.country = country
        update.gender = gender

        update.save()

        messages.success(request, "User updated successfully")
        return redirect("/viewdata")


    d = Users.objects.get(id=id)
    context = {"d": d}
    return render(request, 'edituser.html', context)


def shop(request):

    vehicles = Shop.objects.all()
    context = {"vehicles": vehicles, 'nav':'shop'}
    return render(request, 'shop.html', context)


def signup(request):
    return render(request, 'signup.html')


def signupdata(request):
    if request.method == 'POST':
        username = request.POST.get('s-name')
        email = request.POST.get('s-email')
        password = request.POST.get('s-password')

        signup = User.objects.create_user(username, email, password)
        signup.save()
    return redirect('/login')


def userlogin(request):
    if request.method == "POST":
        l_username = request.POST.get('login-username')
        l_password = request.POST.get('login-password')
        userlog = authenticate(username=l_username, password=l_password)
        if userlog is not None:
            login(request, userlog)
            return redirect('/')
        else:
            messages.error(request, "Username or password is incorrect")
            return redirect('/login')

    return render(request, 'login.html')


def dashboard(request):
    return render(request, 'dashlayout.html')


def viewvehicle(request):
    return render(request, 'viewvehicle.html')

def cart(request):
    return render(request, 'cart.html')


def uploads(request):

    datas = Uploadfiles.objects.all()
    return render(request, 'uploads.html',{'data':datas})


def uploadfiles(request):
    if request.method == "POST":
        image = request.FILES.get('image')
        file = request.FILES.get('file')

        query = Uploadfiles(image=image, file=file)
        query.save()
    return render(request, 'uploads.html')


def addvehicle(request):
    return render(request, 'addvehicle.html', {'nav':'addvehicle'})


def addvehicletodb(request):
    if request.method == 'POST':
        make = request.POST.get('make').title()
        model = request.POST.get('model').title()
        cc = request.POST.get('cc')
        mileage = request.POST.get('mileage')
        fuel_type = request.POST.get('fuel')
        transmission = request.POST.get('transmission')
        year = request.POST.get('yom')
        color = request.POST.get('color')
        available_units = request.POST.get('units')
        photo = request.FILES.get('photo')
        # price = request.POST.get('price')
        # other_photos = request.POST.get('otherphotos')

        query = Shop(make=make, model=model, cc=cc, mileage=mileage, fuel_type=fuel_type,
                     transmission=transmission,  year=year, color=color, available_units=available_units,
                     photo=photo)
        query.save()
        messages.success(request, "Vehicle added successfully")

        return redirect('/addvehicle')

chekigari/templates/addvehicle.html
{% extends 'index.html' %}

{% block title %} Add Vehicle {% endblock %}

{% block main %} {% endblock %}

{% block below-main %}

    <div class="container">
        <form action="{% url 'chekigari:addvehicletodb' %}" method="POST" enctype="multipart/form-data" style="margin-left: 20%; margin-right: 20%; background-color: black; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
                {% csrf_token %}

                <h2 style="text-align: center; color: white">ADD VEHICLE</h2>
            <div style="background-color: white; padding: 50px">
                {% for message in messages %}
                        <div class="alert alert-success alert-dismissible fade show mt-2 mb-2" role="alert">
                          {{ message }}
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>

                    {% endfor %}
                <div class="row form-group">
                <div class="col-6 col-sm-12 col-md-6">
                    <label for="make">Make</label>
                    <select name="make" id="make" class="form-control">
                        <option value="">---</option>
                        <option value="Mazda">Mazda</option>
                    </select>
                </div>
                <div class="col-6 col-sm-12 col-md-6" class="form-control">
                    <label for="model">Model</label>
                    <select name="model" id="model" class="form-control">
                        <option value="">---</option>
                        <option value="CX5">CX5</option>
                        <option value="CX3">CX3</option>
                    </select>
                </div>
            </div>

                <div class="row form-group mt-4">
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="cc">Engine CC</label>
                        <input type="number" class="form-control" id="cc" name="cc">

                    </div>
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="mileage">Mileage</label>
                        <input type="number" class="form-control" id="mileage" name="mileage">
                    </div>
                </div>

                <div class="row form-group mt-4">
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="fuel">Fuel type</label>
                        <select name="fuel" id="fuel" class="form-control">
                            <option value="">---</option>
                            <option value="Petrol">Petrol</option>
                            <option value="Diesel">Diesel</option>
                        </select>

                    </div>
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="transmission">Transmission</label>
                        <select name="transmission" id="transmission" class="form-control">
                            <option value="">---</option>
                            <option value="Manual">Manual</option>
                            <option value="Automatic">Automatic</option>
                        </select>
                    </div>
                </div>

                <div class="row form-group mt-4">
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="yom">Year</label>
                        <input type="number" class="form-control" id="yom" name="yom">

                    </div>
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="color">Color</label>
                        <input type="text" class="form-control" id="color" name="color">
                    </div>
                </div>

                <div class="row form-group mt-4">
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="units">Available units</label>
                        <input type="number" class="form-control" id="units" name="units">

                    </div>
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="vehicleimage">Photo</label>
                        <input type="file" accept="image/*" id="photo" name="photo" class="form-control" >
                    </div>
                </div>

                <div class="row form-group mt-4">
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="otherphotos">Other photos</label>
                        <input type="file" accept="image/*" id="otherphotos" name="otherphotos" class="form-control" disabled>
                    </div>


                </div>


                <div class="row form-group mt-4">
                    <input type="submit" class="btn btn-submit" name="add" value="ADD">
                </div>

            </div>
        </form>
    </div>

{% endblock %}

{% block become-seller %} {% endblock %}

chekigari/templates/messages.html
{% extends 'index.html' %}

{% block main %} {% endblock %}

{% block below-main %}
    <div class="container" style="height: 100vh; margin-bottom: 50px">
    <h2 style="text-align: center; font-weight: 600; margin-top: 20px; color: white; padding: 10px 0px; background-color: black">Messages</h2>

        <div class="row">
            <div class="col-md-4">
              <form>
                <div class="input-group">
                  <input type="search" class="form-control" placeholder="Type here..." size="50">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="button" style="margin-left: 10px;">Search</button>
                  </div>
                </div>
              </form>
            </div>
        </div>

        <table class="table table-hover mt-4">
          <thead>
            <tr>
              <th>ID</th>
              <th>NAME</th>
              <th>PHONE NO</th>
              <th>SUBJECT</th>
              <th>MESSAGE</th>
              <th colspan="2">ACTIONS</th>
            </tr>
          </thead>
          <tbody>

          {% for message in messages %}
            <tr>

              <th>{{message.id }}</th>
              <td>{{message.name }}</td>
              <td>{{ message.phone }}</td>
              <td>{{ message.subject }}</td>
              <td>{{ message.message }}</td>
              <td class="actionBtn">
                  <a href="#" type="button">
                      Edit
                  </a>
                  <a href="/deleteMessage/{{ message.id }}" type="button">
                      Delete
                  </a>
              </td>

            </tr>

          {% endfor %}


          </tbody>
        </table>
    </div>

{% endblock %}


{% block become-seller %}

{% endblock %}

chekigari/templates/register.html
{% extends  'index.html' %}

{% block title %} Register {% endblock %}

{% block main %} {% endblock %}



{% block below-main %}

    <div class="container-fluid" style="margin-bottom: 20px">
        <div class="container">

            <form action="/insert" method="POST" enctype="" style="margin-left: 20%; margin-right: 20%; background-color: black; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
                {% csrf_token %}

                <h2 style="text-align: center; color: white">REGISTRATION FORM</h2>
            <div style="background-color: white; padding: 50px">

                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show mt-2 mb-2" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>

                {% endfor %}

                <div class="row form-group">
                <div class="col-6 col-sm-12 col-md-6">
                    <label for="first-name">First name</label>
                    <input type="text" id="first-name"  name="first-name" class="form-control">
                </div>
                <div class="col-6 col-sm-12 col-md-6">
                    <label for="">Other names</label>
                    <input type="text" id="other-names"  name="other-names" class="form-control">
                </div>
            </div>

                <div class="row form-group mt-4">
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="tel-no">Phone no.</label>
                        <input type="number" class="form-control" id="tel-no" name="tel-no">

                    </div>
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="dob">Date of Birth</label>
                        <input type="date" class="form-control" id="dob" name="dob">
                        <span id="error-message" class="error-message"></span>
                    </div>
                </div>

                <div class="row form-group mt-4">
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email">

                    </div>
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="country">Country</label>
                        <select name="country" id="country" class="form-control">
                            <option value="">Choose country</option>
                            <option value="Kenya">Kenya</option>
                            <option value="Tanzania">Tanzania</option>
                            <option value="Uganda">Uganda</option>
                            <option value="Ethiopia">Ethiopia</option>
                        </select>
                    </div>
                </div>

                <div class="row form-group mt-4">
{#                    <div class="col-6 col-sm-12 col-md-6">#}
{#                        <label for="photo">Upload photo (jpg, png)</label>#}
{#                        <input type="file" class="form-control" id="photo" name="photo">#}
{##}
{#                    </div>#}
{#                    <div class="col-6 col-sm-12 col-md-6">#}
{#                        <label for="company-profile">Company profile (pdf)</label>#}
{#                        <input type="file" class="form-control" id="company-profile" name="company-profile">#}
{#                    </div>#}
                </div>

                <div class="row form-group mt-4">
{#                    <div class="col-6 col-sm-12 col-md-6">#}
{#                        <label for="application-letter">Application letter (word)</label>#}
{#                        <input type="file" class="form-control" id="application-letter" name="application-letter">#}
{##}
{#                    </div>#}
                    <div class="col-6 col-sm-12 col-md-6">
                        <label for="gender">Gender</label>
                        <select name="gender" id="gender" class="form-control">
                            <option value="">Choose gender</option>
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                            <option value="Intersex">Intersex</option>
                        </select>
                    </div>
                </div>

                <div class="row form-group mt-4">
                    <input type="submit" class="btn btn-submit" name="signup" value="SIGN UP">
                </div>

                <div class="row">
                <div class="mb-3 not-registered">
                <p>Already registered? <a href="{% url 'chekigari:login' %}">Log in</a></p>

            </div>
            </div>
            </div>
        </form>
        </div>
    </div>

{% endblock %}

{% block become-seller %}

{% endblock %}

{% block scripts %}

    <script>
        let birthdateInput = document.getElementById('dob');
        let errorMessage = document.getElementById('error-message');

        birthdateInput.addEventListener('change', function() {
            let birthdate = new Date(this.value);
            let today = new Date();
            let age = today.getFullYear() - birthdate.getFullYear();

            if (today.getMonth() < birthdate.getMonth() || (today.getMonth() === birthdate.getMonth() && today.getDate() < birthdate.getDate())) {
                age--;
            }

            if (age < 18) {
                birthdateInput.value = '';
                errorMessage.textContent = 'You must be at least 18 years old.';
            } else {
                errorMessage.textContent = '';
            }
        });
    </script>

{% endblock %}

chekigari/templates/shop.html
{% extends 'index.html' %}
{% load static %}
{% block title %} Shop {% endblock %}
{% block main %}

{% endblock %}

{% block below-main %}
        <div class="container" style="margin-top: 50px; margin-bottom: 50px">
        <h3 >Find your vehicle</h3>
            <div class="row">
            <div class="col">
              <form class="homepage-search">
                  {% csrf_token %}
                <div class="input-group">
{#                    <label for="make">Choose vehicle make</label>#}
                    <select class="form-control edit-form-control" name="make" id="make" required>
                        <option value="">Choose make</option>
                        <option value="">Mazda</option>
                        <option value="">Toyota</option>
                        <option value="">Mercedes Benz</option>
                        <option value="">Nissan</option>

                    </select>
                    <div class="input-group-append">
{#                        <label for="model">Model</label>#}
                        <select class="form-control edit-form-control" name="model" id="model" required>
                            <option value="">Choose model</option>
                            <option value="">Cx1</option>
                            <option value="">Cx2</option>
                            <option value="">Cx3</option>
                            <option value="">Cx4</option>
                            <option value="">Cx5</option>

                        </select>
                  </div>
                    <div class="input-group-append">
                        <input type="number" name="minyear" id="minyear" placeholder="2016" class="form-control" required>
                  </div>
                    <div class="input-group-append">
                        <input type="number" name="maxyear" id="maxyear" placeholder="2023" class="form-control" required>

                  </div>
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="button">Search</button>
                  </div>
                </div>
              </form>
            </div>
        </div>

        </div>
{#        Vehicle display starts here#}
        <div class="vehicles container mt-5">
        {% for vehicle in vehicles %}
            <div class="card">
              <img src="/media/{{vehicle.photo }}" class="card-img-top" alt="{{vehicle.photo }}" style="width: 100%; height: 10rem">
              <div class="card-body">
                <h5 class="card-title">{{ vehicle.make }} {{ vehicle.model }}</h5>
                <hr>
                <p class="card-text">AWD, Leather Seats, Black Interior</p>
                <p class="card-text">Mileage: <b>{{ vehicle.mileage}} Kms </b></p>
                  <p class="card-text">Price: Ksh <b>3,500,000</b></p>
                <a href="{% url 'chekigari:viewvehicle' %}"style="width: 100%" class="btn btn-primary">View details</a>
              </div>
            </div>
        {% endfor %}

    <div class="container mt-5">

    <ul class="pagination">
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
      </li>
      <li class="page-item active current-page" aria-current="page">
        <a class="page-link" href="#">1</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">2</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">3</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="#">Next</a>
      </li>
    </ul>
  </div>


  </div>
{#        Vehicle display ends here#}


    {% endblock %}

chekigari/templates/signup.html
{% extends  'index.html' %}

{% block title %} Login {% endblock %}

{% block main %} {% endblock %}



{% block below-main %}

    <div class="container-fluid" style="">
        <div class="container">

            <form action="{% url 'chekigari:signupdata' %}" method="POST" enctype="" style="margin: 20px 25%; background-color: black; border-radius: 5px; box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
                {% csrf_token %}
                <h2 style="text-align: center; color: white">SIGN UP</h2>
                {% csrf_token %}
            <div style="background-color: white; padding: 50px">
                <div class="row form-group mt-4">
                    <div class="col-6 col-sm-12 col-md-12">
                    <label for="full-name">User name</label>
                    <input type="text" id="s-name"  name="s-name" class="form-control" placeholder="e.g johndave">
                </div>
                </div>
                <div class="row form-group mt-4">
                <div class="col-6 col-sm-12 col-md-12">
                    <label for="login-email">Email</label>
                    <input type="email" id="s-email" name="s-email" class="form-control edit-form-control">
                </div>
            </div>

                <div class="row form-group mt-4">
                    <div class="col-6 col-sm-12 col-md-12">
                        <label for="login-password">Password</label>
                        <input type="password"  class="form-control edit-form-control" id="s-password" name="s-password">


                    </div>

                </div>
                <div class="row form-group mt-4">
                    <div class="col-6 col-sm-12 col-md-12">
                        <label for="repeat-password">Repeat password</label>
                        <input type="password"  class="form-control edit-form-control" id="repeat-password" name="repeat-password" onkeyup="check()">
                        <p id="password_message"></p>

                    </div>

                </div>

                <div class="row form-group mt-4">
                    <input type="submit" class="btn btn-submit" id="signup" name="signup" value="SIGN UP">
                </div>

                <div class="row">
                <div class="mb-3 not-registered">
                <p>Already registered? <a href="{% url 'chekigari:login' %}">Login here</a></p>

            </div>
            </div>
            </div>
        </form>
        </div>
    </div>

{% endblock %}

{% block become-seller %}

{% endblock %}

{% block scripts %}
    <script>
        function check(){
            if (document.getElementById('s-password').value === document.getElementById('repeat-password').value){
                document.getElementById('password_message').innerHTML = 'Passwords match!';
                document.getElementById('password_message').style.color = 'green';
                document.getElementById('signup').disabled = false;
            }else{
                document.getElementById('password_message').innerHTML = "Passwords do not match!";
                document.getElementById('password_message').style.color = "red";
                document.getElementById('signup').disabled = true;
            }
        }
    </script>

{% endblock %}

chekigari/templates/uploads.html
{% extends 'index.html' %}
{% load static %}

{% block main %} {% endblock %}


{% block below-main %}

    <div class="container">


        <form action="{% url 'chekigari:uploadfiles' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

             <div class="row">
        <div class="col-6 col-md-6">
            <label for="">Image</label>
    <input type="file" accept="image/*" name="image" id="image" class="form-control">
    <br>
    <label for="">PDF</label>
    <input type="file" name="file" class="form-control">
        </div>
    </div>
            <input type="submit" value="Submit" class="btn btn-success mt-5">

        </form>


    </div>

    <div class="container">
      <div class="row">

          {% for d in data %}
          <div class="col-md-4">

              <img src="/media/{{ d.image }}" alt="">
              <p>
                  <a target="_blank" href="/media/{{ d.file }}">View file</a>
              </p>

          </div>

          {% endfor %}

      </div>
    </div>

{% endblock %}

{% block become-seller %} {% endblock %}